export interface Course {
  id?: number;
  courseName: string;
  courseKey?: string;
  courseEmail: string;
  courseCoverImageUrl: string;
  courseDescription: string;
  courseCapacity: number;
  }
  // tslint:disable-next-line:max-line-length
  // constructor(courseName: string, courseKey: string, courseEmail: string, courseCoverImageUrl: string, courseDescription: string, courseCapacity: number) {
  //   this.courseName = courseName;
  //   this.courseKey = courseKey;
  //   this.courseEmail = courseEmail;
  //   this.courseCoverImageUrl = courseCoverImageUrl;
  //   this.courseDescription = courseDescription;
  //   this.courseCapacity = courseCapacity;
  // }



// private long id;
// private String course_name;
// private String courseKey;
// private String course_email;
// private String course_cover_image_url;
// private String course_description;
// private int course_capacity;
